import {
  JsonRpcRequest_for_EXPERIMENTAL_changes,
  JsonRpcResponse_for_RpcStateChangesInBlockResponse_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_changes_in_block,
  JsonRpcResponse_for_RpcStateChangesInBlockByTypeResponse_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_congestion_level,
  JsonRpcResponse_for_RpcCongestionLevelResponse_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_genesis_config,
  JsonRpcResponse_for_GenesisConfig_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_light_client_block_proof,
  JsonRpcResponse_for_RpcLightClientBlockProofResponse_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_light_client_proof,
  JsonRpcResponse_for_RpcLightClientExecutionProofResponse_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_maintenance_windows,
  JsonRpcResponse_for_Array_of_Range_of_uint64_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_protocol_config,
  JsonRpcResponse_for_RpcProtocolConfigResponse_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_receipt,
  JsonRpcResponse_for_RpcReceiptResponse_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_split_storage_info,
  JsonRpcResponse_for_RpcSplitStorageInfoResponse_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_tx_status,
  JsonRpcResponse_for_RpcTransactionResponse_and_RpcError,
  JsonRpcRequest_for_EXPERIMENTAL_validators_ordered,
  JsonRpcResponse_for_Array_of_ValidatorStakeView_and_RpcError,
  JsonRpcRequest_for_block,
  JsonRpcResponse_for_RpcBlockResponse_and_RpcError,
  JsonRpcRequest_for_broadcast_tx_async,
  JsonRpcResponse_for_CryptoHash_and_RpcError,
  JsonRpcRequest_for_broadcast_tx_commit,
  JsonRpcRequest_for_changes,
  JsonRpcRequest_for_chunk,
  JsonRpcResponse_for_RpcChunkResponse_and_RpcError,
  JsonRpcRequest_for_client_config,
  JsonRpcResponse_for_RpcClientConfigResponse_and_RpcError,
  JsonRpcRequest_for_gas_price,
  JsonRpcResponse_for_RpcGasPriceResponse_and_RpcError,
  JsonRpcRequest_for_health,
  JsonRpcResponse_for_Nullable_RpcHealthResponse_and_RpcError,
  JsonRpcRequest_for_light_client_proof,
  JsonRpcRequest_for_network_info,
  JsonRpcResponse_for_RpcNetworkInfoResponse_and_RpcError,
  JsonRpcRequest_for_next_light_client_block,
  JsonRpcResponse_for_RpcLightClientNextBlockResponse_and_RpcError,
  JsonRpcRequest_for_query,
  JsonRpcResponse_for_RpcQueryResponse_and_RpcError,
  JsonRpcRequest_for_send_tx,
  JsonRpcRequest_for_status,
  JsonRpcResponse_for_RpcStatusResponse_and_RpcError,
  JsonRpcRequest_for_tx,
  JsonRpcRequest_for_validators,
  JsonRpcResponse_for_RpcValidatorResponse_and_RpcError,
} from './types';

/**
 * This file was auto-generated by a script.
 * Do not make direct changes to the file.
 */
export type MethodMap = {
  block: {
    request: JsonRpcRequest_for_block;
    response: JsonRpcResponse_for_RpcBlockResponse_and_RpcError;
  };
  broadcast_tx_async: {
    request: JsonRpcRequest_for_broadcast_tx_async;
    response: JsonRpcResponse_for_CryptoHash_and_RpcError;
  };
  broadcast_tx_commit: {
    request: JsonRpcRequest_for_broadcast_tx_commit;
    response: JsonRpcResponse_for_RpcTransactionResponse_and_RpcError;
  };
  changes: {
    request: JsonRpcRequest_for_changes;
    response: JsonRpcResponse_for_RpcStateChangesInBlockResponse_and_RpcError;
  };
  chunk: {
    request: JsonRpcRequest_for_chunk;
    response: JsonRpcResponse_for_RpcChunkResponse_and_RpcError;
  };
  client_config: {
    request: JsonRpcRequest_for_client_config;
    response: JsonRpcResponse_for_RpcClientConfigResponse_and_RpcError;
  };
  EXPERIMENTAL_changes: {
    request: JsonRpcRequest_for_EXPERIMENTAL_changes;
    response: JsonRpcResponse_for_RpcStateChangesInBlockResponse_and_RpcError;
  };
  EXPERIMENTAL_changes_in_block: {
    request: JsonRpcRequest_for_EXPERIMENTAL_changes_in_block;
    response: JsonRpcResponse_for_RpcStateChangesInBlockByTypeResponse_and_RpcError;
  };
  EXPERIMENTAL_congestion_level: {
    request: JsonRpcRequest_for_EXPERIMENTAL_congestion_level;
    response: JsonRpcResponse_for_RpcCongestionLevelResponse_and_RpcError;
  };
  EXPERIMENTAL_genesis_config: {
    request: JsonRpcRequest_for_EXPERIMENTAL_genesis_config;
    response: JsonRpcResponse_for_GenesisConfig_and_RpcError;
  };
  EXPERIMENTAL_light_client_block_proof: {
    request: JsonRpcRequest_for_EXPERIMENTAL_light_client_block_proof;
    response: JsonRpcResponse_for_RpcLightClientBlockProofResponse_and_RpcError;
  };
  EXPERIMENTAL_light_client_proof: {
    request: JsonRpcRequest_for_EXPERIMENTAL_light_client_proof;
    response: JsonRpcResponse_for_RpcLightClientExecutionProofResponse_and_RpcError;
  };
  EXPERIMENTAL_maintenance_windows: {
    request: JsonRpcRequest_for_EXPERIMENTAL_maintenance_windows;
    response: JsonRpcResponse_for_Array_of_Range_of_uint64_and_RpcError;
  };
  EXPERIMENTAL_protocol_config: {
    request: JsonRpcRequest_for_EXPERIMENTAL_protocol_config;
    response: JsonRpcResponse_for_RpcProtocolConfigResponse_and_RpcError;
  };
  EXPERIMENTAL_receipt: {
    request: JsonRpcRequest_for_EXPERIMENTAL_receipt;
    response: JsonRpcResponse_for_RpcReceiptResponse_and_RpcError;
  };
  EXPERIMENTAL_split_storage_info: {
    request: JsonRpcRequest_for_EXPERIMENTAL_split_storage_info;
    response: JsonRpcResponse_for_RpcSplitStorageInfoResponse_and_RpcError;
  };
  EXPERIMENTAL_tx_status: {
    request: JsonRpcRequest_for_EXPERIMENTAL_tx_status;
    response: JsonRpcResponse_for_RpcTransactionResponse_and_RpcError;
  };
  EXPERIMENTAL_validators_ordered: {
    request: JsonRpcRequest_for_EXPERIMENTAL_validators_ordered;
    response: JsonRpcResponse_for_Array_of_ValidatorStakeView_and_RpcError;
  };
  gas_price: {
    request: JsonRpcRequest_for_gas_price;
    response: JsonRpcResponse_for_RpcGasPriceResponse_and_RpcError;
  };
  health: {
    request: JsonRpcRequest_for_health;
    response: JsonRpcResponse_for_Nullable_RpcHealthResponse_and_RpcError;
  };
  light_client_proof: {
    request: JsonRpcRequest_for_light_client_proof;
    response: JsonRpcResponse_for_RpcLightClientExecutionProofResponse_and_RpcError;
  };
  network_info: {
    request: JsonRpcRequest_for_network_info;
    response: JsonRpcResponse_for_RpcNetworkInfoResponse_and_RpcError;
  };
  next_light_client_block: {
    request: JsonRpcRequest_for_next_light_client_block;
    response: JsonRpcResponse_for_RpcLightClientNextBlockResponse_and_RpcError;
  };
  query: {
    request: JsonRpcRequest_for_query;
    response: JsonRpcResponse_for_RpcQueryResponse_and_RpcError;
  };
  send_tx: {
    request: JsonRpcRequest_for_send_tx;
    response: JsonRpcResponse_for_RpcTransactionResponse_and_RpcError;
  };
  status: {
    request: JsonRpcRequest_for_status;
    response: JsonRpcResponse_for_RpcStatusResponse_and_RpcError;
  };
  tx: {
    request: JsonRpcRequest_for_tx;
    response: JsonRpcResponse_for_RpcTransactionResponse_and_RpcError;
  };
  validators: {
    request: JsonRpcRequest_for_validators;
    response: JsonRpcResponse_for_RpcValidatorResponse_and_RpcError;
  };
};
export type RpcMethod = keyof MethodMap;
export type ApiRequest<M extends RpcMethod> = MethodMap[M]['request'];
export type ApiResponse<M extends RpcMethod> = MethodMap[M]['response'];
