name: Daily OpenAPI Spec Fetch

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      openapi_url:
        description: 'URL to fetch OpenAPI spec from (optional, overrides repository variable)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: openapi-generation
  cancel-in-progress: false

jobs:
  fetch-and-generate:
    name: Fetch OpenAPI Spec and Generate Code & Types
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.15.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Determine OpenAPI URL
        id: url-config
        run: |
          if [[ -n "${{ inputs.openapi_url }}" ]]; then
            echo "Using URL from workflow input"
            OPENAPI_URL="${{ inputs.openapi_url }}"
          elif [[ -n "${{ vars.INPUT_JSON_URL }}" ]]; then
            echo "Using URL from repository variable"
            OPENAPI_URL="${{ vars.INPUT_JSON_URL }}"
          else
            echo "::error::No OpenAPI URL provided. Please set the INPUT_JSON_URL repository variable or provide URL via workflow dispatch."
            exit 1
          fi
          echo "openapi_url=${OPENAPI_URL}" >> $GITHUB_OUTPUT

      - name: Download OpenAPI spec
        run: |
          echo "Downloading OpenAPI spec from: ${{ steps.url-config.outputs.openapi_url }}"
          curl -L -o codegen/openapi.json "${{ steps.url-config.outputs.openapi_url }}"

      - name: Format code
        run: pnpm run format

      - name: Check for changes in OpenAPI spec
        id: git-check
        run: |
          git add codegen/openapi.json
          if git diff --staged --quiet -- codegen/openapi.json; then
            echo "No changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate code & types
        if: steps.git-check.outputs.has_changes == 'true'
        run: pnpm run codegen

      - name: Format generated code
        if: steps.git-check.outputs.has_changes == 'true'
        run: pnpm run format

      - name: Create or Update Pull Request
        if: steps.git-check.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/update-openapi-spec
          base: main
          commit-message: 'feat: update generated files from latest OpenAPI spec'
          title: 'feat: update generated files from latest OpenAPI spec'
          body: |
            This PR updates the OpenAPI specification from the upstream source and regenerates files based on OpenAPI changes.

            - Source: ${{ steps.url-config.outputs.openapi_url }}
            - Generated by: Daily OpenAPI Spec Fetch workflow
